###################
## OPC-UA Filter ##
###################

namespace: '/'
  #

topics:
  - /joint_states

services:
  - /ewdl_driver/start_homing
  - /ewdl_driver/start_motion
  - scene_server/scene
  - /moving_arm/go
  - /moving_arm/move
  - /moving_arm/stop
  - /moving_full/go
  - /moving_full/move
  - /moving_full/stop
  - /tasking_arm/pick
  - /tasking_arm/place
  - /tasking_arm/stop
