###################
## OPC-UA Filter ##
###################

namespace: '/'
  #

topics:
  - /joint_states

services:
  - /ewdl_driver/start_homing
  - /ewdl_driver/start_motion
  - /moving_node/go
  - /moving_node/move
  - /moving_node/stop
  - /tasking_node/pick
  - /tasking_node/place
  - /tasking_node/stop
